/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/deshboard/AppBar.vue')['default']
    Content: typeof import('./src/components/deshboard/Content.vue')['default']
    Navigation: typeof import('./src/components/deshboard/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMedia: typeof import('./src/components/admin/selectMedia.vue')['default']
    TableContent: typeof import('./src/components/table/TableContent.vue')['default']
    UploadMedia: typeof import('./src/components/other/UploadMedia.vue')['default']
  }
}
